#!/bin/bash

HOMEPATH="../scripts"
WORKPATH="../work"
CONFIGFILEPATH="../input/config_files"


function summaries_budget_violation(){
    # this is just for record. this function cannot be called directly
    master.sh prepare_all_pipelines bd1 bd2 bd3 bd4 ph1 ph2 ph3 ph4 vn1 vn2 vn3 vn4 id1 id2 id3 id4 th1 th2 th3 th4
    #master.sh prepare_all_pipelines bd_startmonth3_ bd_startmonth7_
    ./run.sh
    python ../scripts/gather_outputs.py -i
    # Run with --suppress_output commented for the last figure in pipe_sim.sbatch
    python ../scripts/second_pipeline.py
    ./run.sh
    python ../scripts/gather_outputs.py -s
    # get sim_summaries.csv
    # one for threshold = gm
    # another for threshold = no_groups
   
}


function bd(){
    # this is just for record. this function cannot be called directly
    master.sh prepare_all_pipelines bd1 bd2 bd3 bd4 ph1 ph2 ph3 ph4 vn1 vn2 vn3 vn4 id1 id2 id3 id4 th1 th2 th3 th4
    #master.sh prepare_all_pipelines bd_startmonth3_ bd_startmonth7_
    ./run.sh
    python ../scripts/fill_gaps.py
    python ../scripts/gather_outputs.py -i
    # Run with --suppress_output commented for the last figure in pipe_sim.sbatch
    python ../scripts/second_pipeline.py
    ./run.sh
    python ../scripts/gather_outputs.py -s
    collect
}

function ph(){
    # this is just for record. this function cannot be called directly
    master.sh prepare_all_pipelines ph1 ph2
    ./run.sh
    python ../scripts/fill_gaps.py
    python ../scripts/gather_outputs.py -i
    python ../scripts/second_pipeline.py
    ./run.sh
    python ../scripts/gather_outputs.py -s
    collect
}

function collect(){
    cd ..
    (
        find . -type f -iname 'sim_summaries.csv' -print0 | xargs -0 cat | head -n 1
  find . -type f -iname 'sim_summaries.csv' -print0 | xargs -0 cat | sort | uniq | grep -iv "^network"
) > results/int_summaries.csv
}

function genint(){
    create_directories
    prefix="${1:-bd}" # if no arguments given, uses bd_config.json
    python3 ${HOMEPATH}/generate_intervention_configs.py ${CONFIGFILEPATH}/${prefix,,}config.json
}

if [[ $# == 0 ]]; then
   echo "Here are the options:"
   grep "^function" $BASH_SOURCE | sed -e 's/function/  /' -e 's/[(){]//g' -e '/IGNORE/d'
else
   eval $1 ${@:2}
fi