#!/bin/bash
# Rough script to regulate slurm jobs, so no more than 10,000 are pending at once (for batch submissions, where batch size <=100)

speed=.1
usr=`whoami`
if [ $# != 1 ]; then
    rsize=9901;
    qsize=9901;
    tsize=9901;
else 
    rsize=$1;
    qsize=9901;
    tsize=9901;
fi

while [ 1 ];
do
   #rstatus=`squeue -u $usr -o "%t" -h | grep R | wc -l`
   rstatus=`squeue -u $usr -o "%t" -h -t running -r | wc -l` 
   #qstatus=`squeue -u $usr -o "%t" -h | grep PD | wc -l`
   qstatus=`squeue -u $usr -o "%t" -h -t pending -r | wc -l`
   tstatus=`squeue -u $usr -o "%t" -h -r | wc -l`
   #echo $tstatus

   if [[ $rstatus -ge $rsize ]] || [[ $qstatus -ge $qsize ]] || [[ $tstatus -ge $tsize ]]; then
   echo -ne "\r\033[K|o            $rstatus running and $qstatus in queue. $tstatus total." #Cap: $rsize running and $qsize queue. Waiting ...";
      sleep .5;
   echo -ne "\r\033[K\ o           $rstatus running and $qstatus in queue. $tstatus total." #Cap: $rsize running and $qsize queue. Waiting ...";
      sleep $speed;
   echo -ne "\r\033[K\  o          $rstatus running and $qstatus in queue. $tstatus total." #Cap: $rsize running and $qsize queue. Waiting ...";
      sleep $speed;
   echo -ne "\r\033[K\   o         $rstatus running and $qstatus in queue. $tstatus total." #Cap: $rsize running and $qsize queue. Waiting ...";
      sleep $speed;
   echo -ne "\r\033[K\    o        $rstatus running and $qstatus in queue. $tstatus total." #Cap: $rsize running and $qsize queue. Waiting ...";
      sleep $speed;
   echo -ne "\r\033[K|     o       $rstatus running and $qstatus in queue. $tstatus total." #Cap: $rsize running and $qsize queue. Waiting ...";
      sleep $speed;
   echo -ne "\r\033[K|      o      $rstatus running and $qstatus in queue. $tstatus total." #Cap: $rsize running and $qsize queue. Waiting ...";
      sleep $speed;
   echo -ne "\r\033[K|       o     $rstatus running and $qstatus in queue. $tstatus total." #Cap: $rsize running and $qsize queue. Waiting ...";
      sleep $speed;
   echo -ne "\r\033[K|        o    $rstatus running and $qstatus in queue. $tstatus total." #Cap: $rsize running and $qsize queue. Waiting ...";
      sleep $speed;
   echo -ne "\r\033[K|         o   $rstatus running and $qstatus in queue. $tstatus total." #Cap: $rsize running and $qsize queue. Waiting ...";
      sleep $speed;
   echo -ne "\r\033[K|          _  $rstatus running and $qstatus in queue. $tstatus total." #Cap: $rsize running and $qsize queue. Waiting ...";
   echo -ne "\r\033[K|          ^  $rstatus running and $qstatus in queue. $tstatus total." #Cap: $rsize running and $qsize queue. Waiting ...";
      sleep $speed;
   echo -ne "\r\033[K|          _  $rstatus running and $qstatus in queue. $tstatus total." #Cap: $rsize running and $qsize queue. Waiting ...";
      sleep 1;
   else
      break;
   fi
done
